/*
 * bin2c: A Program to convert binary data into C source code
 * Copyright by Apple Open Source
 * http://www.opensource.apple.com/source/libpcap/libpcap-16/libpcap/msdos/bin2c.c
 *
 * Modified for fully C-style
 * Copyright 2012 by ipfans
 *
 */

#include <sys/stat.h>
#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <time.h>

static void Abort (char *fmt,...)
{
    va_list args;
    va_start (args, fmt);
    vfprintf (stderr, fmt, args);
    va_end (args);
    exit (1);
}

int main (int argc, char **argv)
{
    FILE    *inFile;
    FILE    *outFile = stdout;
    time_t  now = time (NULL);
    int     ch, i;

    if (argc != 2)
        Abort ("Usage: %s bin-file [> result]\n", argv[0]);

    if ((inFile = fopen(argv[1],"rb")) == NULL)
        Abort ("Cannot open %s\n", argv[1]);

    struct stat buf;
    int result = stat(argv[1], &buf);
    if( result != 0 )
        Abort ("Cannot stat %s\n", argv[1]);
    
    fprintf (outFile,
        "/* data statements for file %s at %.24s */\n"
        "/* Generated by BIN2C, ipfan 2012 */\n"
        "\n"
        "unsigned char hexData[%lld] = {",
        argv[1], ctime(&now), buf.st_size);

    i = 0;
    while ((ch = fgetc(inFile)) != EOF)
    {
        if (i++ % 12 == 0)
            fputs ("\n  ", outFile);
        fprintf (outFile, "0x%02X,", ch);
    }
    fprintf(outFile,"\n}\n");
    fclose (inFile);
    return (0);
}